### ISSUE TITLE
Add Nomatch page

### ISSUE THREAD

**Issue by sandra9711** [GDSC-MACE/MaceNotes#12]
Add 404 page at [Nomatch](https://github.com/GDSC-MACE/MaceNotes/tree/main/src/Pages/Nomatch)

**Comment by programmerraja** [comment]
@sandra9711 can I work on this ?

**Comment by programmerraja** [comment]
@sandra9711  is this okay
![Screenshot from 2021-10-20 19-54-48](https://user-images.githubusercontent.com/44333589/138112234-b15fc249-0e7a-4736-b0d4-695a65e102b3.png)
