### ISSUE TITLE
Develop home page

### ISSUE THREAD

**Issue by sandra9711** [GDSC-MACE/MaceNotes#5]
Develop the Homepage of the site according to the given UI
[figma design](https://www.figma.com/file/zHfpGg2HLJxtMoOxJK1MzG/MaceNotes?node-id=0%3A1)

**Comment by arialdyscv** [comment]
Hi @sandra9711 i would like to work on this for the hacktoberfest, please assign it to me :)

**Comment by sandra9711** [comment]
@arialdyscv  Please go ahead
